import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for The Tree of Knowledge.',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0a1424] text-[#c0bab0]" style={{ fontFamily: "'Nunito', sans-serif" }}>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="inline-flex items-center gap-2 text-[#f0d888] hover:text-[#f0d888]/80 mb-8 text-sm">
          ← Back to Tree of Knowledge
        </Link>
        
        <h1 className="text-3xl font-bold text-[#f0ece4] mb-2" style={{ fontFamily: "'Lora', serif" }}>Terms of Service</h1>
        <p className="text-sm text-white/30 mb-8">Last updated: March 16, 2026</p>

        <div className="space-y-8 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Agreement to Terms</h2>
            <p>By accessing The Tree of Knowledge ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part, you may not access the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Description of Service</h2>
            <p>The Tree of Knowledge is a free, AI-powered educational tool that allows users to explore topics across all branches of human knowledge. The Service generates educational content using artificial intelligence.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Service for any illegal purpose</li>
              <li>Attempt to overwhelm, attack, or exploit the Service</li>
              <li>Use automated systems to access the Service excessively</li>
              <li>Interfere with other users' access to the Service</li>
              <li>Reverse engineer or attempt to extract source code</li>
              <li>Use the Service to generate harmful, misleading, or illegal content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">AI-Generated Content</h2>
            <p className="mb-3">Content on this Service is generated by artificial intelligence. While we strive for accuracy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-generated content may contain errors or inaccuracies</li>
              <li>Content is for educational purposes only, not professional advice</li>
              <li>You should verify important information from authoritative sources</li>
              <li>We do not guarantee the completeness or reliability of any content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Intellectual Property</h2>
            <p>The Service's design, code, and branding are owned by NumberOneSon Software. AI-generated educational content is provided for personal, non-commercial use. You may not reproduce or redistribute the Service itself.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Donations</h2>
            <p>Donations to support the Service are voluntary and non-refundable. Donations do not grant any special access or privileges. Payment processing is handled by Stripe.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Service Availability</h2>
            <p>We strive to maintain the Service but do not guarantee uninterrupted access. We may modify, suspend, or discontinue the Service at any time without notice. We are not liable for any downtime or service interruptions.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Limitation of Liability</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Indemnification</h2>
            <p>You agree to indemnify and hold harmless NumberOneSon Software from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Governing Law</h2>
            <p>These Terms shall be governed by the laws of the State of California, United States, without regard to conflict of law provisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Changes to Terms</h2>
            <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ece4] mb-3">Contact</h2>
            <p>Questions about these Terms? Contact us at: <a href="mailto:legal@numberonesonsoftware.com" className="text-[#f0d888] hover:underline">legal@numberonesonsoftware.com</a></p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10 text-center text-sm text-white/30">
          <p>© 2026 NumberOneSon Software. All rights reserved.</p>
        </div>
      </div>
    </div>
  )
}
